version: 2.1
jobs:
  build:
    docker:
      - image: xsans02/docker:ubuntu
    steps:
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/vayu/startBuild
      - run: bash startBuild stable clang
