version: 2.1
jobs:
  build:
    docker:
      - image: zycromerz/kerneldocker:v2
    steps:
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/vayu/startBuild
      - run: bash startBuild beta gcc
