version: 2.1
jobs:
  build:
    docker:
      - image: xyzuan/xdocker:latest
    steps:
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip_test/doBuild
      - run: bash doBuild stable
