version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: git clone --depth=1 https://github.com/XSans02/kernel_sdm660.git -b eas-test kernel
      - run: cd kernel
      - run: bash build oldcam
