version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip/start
      - run: bash start beta oldcam
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip/build
      - run: bash build
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip/push
      - run: bash push
