version: 2.1
jobs:
  no_output_timeout: 6h
  build:
    docker:
      - image: zycromerz/kerneldocker:v3
    steps: 
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/vayu/doBuild
      - run: bash doBuild beta clang14-llvm