version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: git clone --depth=1 https://github.com/XSans02/halcyon_kernel_xiaomi_sdm660 -b eas-12-bpf kernel
      - run: cd kernel
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip3/build
      - run: bash build oldcam
