version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run: wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip/doBuild
      - run: bash doBuild beta oldcam clang
