version: 2.1
jobs:
  compile:
   docker:
      - image: zycromerz/kerneldocker:v3
   steps:
      - run:
          command: |
            wget https://raw.githubusercontent.com/XSans02/CI_Script/main/vayu/doBuild
            bash doBuild beta clang14-llvm
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
