version: 2.1
jobs:
  build:
    docker:
      - image: xyzuan/xdocker:latest
    steps:
      - run: git clone https://github.com/XSans02/CI_Script .
      - run: cd ./tulip
      - run: bash build.sh
